### PR TITLE
Dark Mode for Windows + small QOL improvement

### PR DESCRIPTION
**Pull request by eengnr**
I've been using this for quite a while now and didn't have any issues so far.
The dark mode is activated with the UI settings in Windows.

### CODE REVIEW

**Comment by trteodor** [comment]
Compiled on Qt5.12.0, not tested well - but thanks man for dark mode! :)  Great job! ;)

**Comment by Usha-Rajanna** [comment]
Build successfully locally and DLT viewer is working fine

**Comment by eengnr** [comment]
> Build successfully locally and DLT viewer is working fine, But I can only figure the QOL change "cancel" to "save". Can you please give the steps to Verify the Changes.

Yes, it's "Save" instead of "Cancel" in the dialog and Ctrl+X copies a selected line just like Ctrl+C instead of showing the annoying popup. If you hit Ctrl+X by accident instead of Ctrl+C, the selection is then copied anyways!

**Comment by Usha-Rajanna** [comment]
> > Build successfully locally and DLT viewer is working fine, But I can only figure the QOL change "cancel" to "save". Can you please give the steps to Verify the Changes.
> 
> Yes, it's "Save" instead of "Cancel" in the dialog and Ctrl+X copies a selected line just like Ctrl+C instead of showing the annoying popup. If you hit Ctrl+X by accident instead of Ctrl+C, the selection is then copied anyways!

**Comment by Usha-Rajanna** [comment]
> > > Build successfully locally and DLT viewer is working fine, But I can only figure the QOL change "cancel" to "save". Can you please give the steps to Verify the Changes.
> > 
> > 
> > Yes, it's "Save" instead of "Cancel" in the dialog and Ctrl+X copies a selected line just like Ctrl+C instead of showing the annoying popup. If you hit Ctrl+X by accident instead of Ctrl+C, the selection is then copied anyways!

@eengnr 
I have verified the functionality as above and its working fine But I am not clear to verify Dark Mode for Windows.

**Comment by Usha-Rajanna** [comment]
I have able to test all the steps given by Developer and its working as expected.
1. In search form I can see **Cancel** is changes to **Save** and the text given is saved when we hit the search again.
2. Ctrl+X is working as copy.
3. Dark mode for Windows - Start-> type Dark-> Turn on dark mode System wide-> custom-> change the dark mode of App-> restart the DLT viewer and the setting is applied to DLT-viewer.

All checks are working Fine.

**Pull request merged**
