### PR TITLE
QT6: Batch scripts update

### PR DESCRIPTION
**Pull request by stephanvoigt**
* tested with Qt 5.15.2 and Qt 6.2.2
* tested on Windows (MSVC 2019) and Linux (gcc 11)

* batch files support Qt5 and Qt6

### CODE REVIEW

**Comment by alexmucde** [comment]
@stephanvoigt 
Thanks for the contribution. Several checks fails, please check.
Please allso add the signed off statement to the commit message.
The PR is very big. Perhaps you can also split the changes in smaller PRs, so that we can do a step by step integration.

**Comment by stephanvoigt** [comment]
I think I can split this PR in batch, CMake and source files by the end of this week.

**Comment by alexmucde** [comment]
@stephanvoigt Sorry for the delay, i had very busy weeks. This PR does not show any conflicts, but please check again. It would be great to get DLT Viewer running with Qt5 and Qt6.

**Comment by alexmucde** [comment]
Replaced by QT 6 support code changes #324

**Pull request closed without merging**
