### PR TITLE
QT6: Added support for QT6

### PR DESCRIPTION
**Pull request by stephanvoigt**
Depends on https://github.com/COVESA/dlt-viewer/pull/245
Depends on https://github.com/COVESA/dlt-viewer/pull/236

* tested with Qt 5.15.2 and Qt 6.2.3
* tested on Windows (MSVC 2022) and Linux (gcc 11)

* replaced QRegExp with QRegularExpression
* replaced qSort with std::sort
* replaced QString!=0 with QString!=nullptr
* replaced QByteArray.append(QString) with QByteArray.append(QByteArray)
* replaced sprintf() with asprintf()
* replaced load() with loadRelaxed()
* replaced store() with storeRelaxed()
* added ifdefs for Qt < 5.14

Signed-off-by: Stephan Voigt <stephan.voigt2121@gmx.de>

### CODE REVIEW

**Comment by alexmucde** [comment]
@stephanvoigt @rus0000 Ruslan is currently working on bigger chnages regarding CMake Files. We have to sync yours and Ruslans work.

**Comment by stephanvoigt** [comment]
@alexmucde 
These build jobs fail, because QT6 support requires at least Qt 5.14.0 or at least Qt 6.2.0, to avoid #ifdef.
Ubuntu 18.04 is testing against Qt 5.9.5
Windows against Qt 5.12.12
MacOSX against Qt 5.15.2

**Comment by stephanvoigt** [comment]
> @stephanvoigt @rus0000 Ruslan is currently working on bigger changes regarding CMake Files. We have to sync yours and Ruslans work.

Done. -> https://github.com/COVESA/dlt-viewer/pull/245

**Comment by stephanvoigt** [comment]
> @alexmucde These build jobs fail, because QT6 support requires at least Qt 5.14.0 or at least Qt 6.2.0, to avoid #ifdef. Ubuntu 18.04 is testing against Qt 5.9.5 Windows against Qt 5.12.12 MacOSX against Qt 5.15.2

@alexmucde
Added ifdefs where needed, to support Qt 5.5.

**Comment by Gen5WO** [comment]
Hey @stephanvoigt , I am new on the block! I did something similar to this Merge Request, tho I went with some slightly different approaches. Since I am fairly new with QT and C++ in general, I was wondering if you could take some time to answer a couple questions: 

1. Why did you do `QString!=nullptr` instead of `!QString.isNull()`?
2. Why `QByteArray.append(QByteArray)` instead of `QByteArray.append(QString.toUtf8())

Thanks in advance!

**Comment by alexmucde** [comment]
@stephanvoigt Sorry for the delay, i had very busy weeks. We have now a lot of conflicts, because of some other pull reuests in between. Can you provide a new pull request with all your changes updated for the master and close the current pull request?

**Comment by alexmucde** [comment]
Replaced by QT 6 support code changes #324

**Pull request closed without merging**
