### PR TITLE
Filter Range should Enabled/Disabled on Filter Enabled option

### PR DESCRIPTION
**Pull request by Manik-ltts**
Signed-off-by: Manik Fulpagar [manik.fulpagar@ltts.com](mailto:manik.fulpagar@ltts.com)

### CODE REVIEW

**Review by alexmucde — APPROVED** [review]
Tested and works as expected.

**Review by alexmucde — CHANGES_REQUESTED** [review]
Please add signed off statement to the commit comment.

**Comment by Manik-ltts** [comment]
signed off statement added

**Comment by Manik-ltts** [comment]
> Please add signed off statement to the commit comment.

done

**Review by alexmucde — APPROVED** [review]

**Pull request merged**
