### PR TITLE
fix Sorting by Lifecycle, startup time #307 

### LINKED ISSUE #307: Sorting by Lifecycle, startup time
Currently sorting by timestamp is only supported for a whole file, but not for dlt files containing several lifecycle.
Also startup time since the beginning of a lifecycle should be calculated and shown.

Feedback from Linkedin.

### PR DESCRIPTION
**Pull request by eaj40**
fix #307

### CODE REVIEW

**Comment by alexmucde** [comment]
I do not see any useful code in there wich solves any issue or provides any new functionality.

**Comment by alexmucde** [comment]
@eaj40 I still do not know how this PR will solve the issue. Identifying lifecycles in a DLT file is a complex topic and cannot be solved by a single line.
1) The Lifecycles of the DLT must be identified
2) Sorting by timestamp must be done based on the identified lifecycles

**Comment by eaj40** [comment]
Please see my comments

  1.  The Lifecycles of the DLT must be identified
[joe] resets when connected over TCP is identified

  1.  Sorting by timestamp must be done based on the identified lifecycles

[joe] Sorting by timestamp starts from 0, after reset. This is already supported feature


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by eaj40** [comment]
Resets when connected over following, does it complete lifecycles
Serial
INTERFACETYPE_UDP
INTERFACETYPE_TCP

**Pull request closed without merging**
