### PR TITLE
Dltviewerconflicts

### PR DESCRIPTION
**Pull request by Usha-Rajanna**

### CODE REVIEW

**Comment by alexmucde** [comment]
Still some issues with Github Actions build?

**Comment by Usha-Rajanna** [comment]
@alexmucde yes, as mentioned need to update workflow as it will download 5.12.12 qt to build this source code.

**Comment by alexmucde** [comment]
@Usha-Rajanna Please set Qt5.15.2 and MSVC2019 as default, so that build will not fail. If build is not failing anymore, i will integrate.

**Comment by Usha-Rajanna** [comment]
@alexmucde there are some changes needed , Ruslan have given the inputs , so once update accordingly we can run with QT 6.4.1

**Comment by alexmucde** [comment]
Replaced by QT 6 support code changes #324

**Pull request closed without merging**
