### PR TITLE
Simplify handling of logging only mode in log table view

### PR DESCRIPTION
**Pull request by vifactor**
With this MR logging only mode is handled separately before any message decoding happens. Before this MR, although msg was default-assigned in one of the if-cases, it still was non-empty due to multiple decodings happening in the data-method for values of `role`-variable other than `DisplayRole`.

### CODE REVIEW

**Comment by alexmucde** [comment]
@vifactor Are you able to test this in an Online Logging use case?

**Comment by alexmucde** [comment]
I have tried it with enabling and disabling this feature and it works, at least in the offline mode.

**Comment by vifactor** [comment]
I tried in offline too. I will check it in online a bit later

**Comment by vifactor** [comment]
online mode seem to work too:
image

**Pull request merged**
