### PR TITLE
Abi in MacOS artifacts

### PR DESCRIPTION
**Pull request by hannesa2**
It's about to have a x86 and an arm64 version for MacOS
image

image

### CODE REVIEW

**Comment by hannesa2** [comment]
@bunty95 are our MacOS build artifact a multi architecture artifacts, which makes this pull request obsolete ?

**Comment by bunty95** [comment]
@hannesa2 current builds are processer specific. 
I don't see how this is different from what we already have available.

**Comment by hannesa2** [comment]
current situation 
image

**Comment by bunty95** [comment]
Yes, we will need this then.

**Pull request merged**
