### PR TITLE
Add qt version define comparison

### PR DESCRIPTION
**Pull request by asgawa**
These functions were introduced in Qt 5.14
 - Qt::endl https://doc.qt.io/qt-5/qt.html#endl
 - QAtomicInt::loadRelaxed https://doc.qt.io/qt-5/qatomicinteger.html#loadRelaxed

Signed-off-by: Shinhoon Kang <asgawa@gmail.com>

### CODE REVIEW

**Comment by asgawa** [comment]
Actually, I use 5.12.3 for embedded target.
And it failed to compile that is on commit message.

**Comment by alexmucde** [comment]
Please provide a signed off statement in your commit message.
Is it also compiling with Qt6? We have no Qt6 CI build yet.

**Comment by asgawa** [comment]
No I do not use Qt6,
But added define is range (version >= 5.14 || version >= 6.0)
I will build with Qt6 until tommorow. Thanks for your fast feedback.

**Comment by asgawa** [comment]
With Qt 6.4.2, it compiled fine.
Thank you.

**Comment by asgawa** [comment]
@alexmucde Is there anything to do?

**Comment by alexmucde** [comment]
@asgawa Please add the signed off statement to the commit message or send it to me and i will update the comment when merging (see an example in older commits).

**Comment by alexmucde** [comment]
Example from me:
Signed-off-by: Alexander Wenzel <Alexander.AW.Wenzel@bmw.de>

**Comment by asgawa** [comment]
> Example from me: Signed-off-by: Alexander Wenzel [Alexander.AW.Wenzel@bmw.de](mailto:Alexander.AW.Wenzel@bmw.de)

Thank you!
Signed-off-by: Shinhoon Kang [asgawa@gmail.com](mailto:asgawa@gmail.com)

**Pull request merged**
