### PR TITLE
Run unit tests for Linux on CI

### PR DESCRIPTION
**Pull request by vifactor**
This adds a step into Linux pipeline to build and run unit tests

### CODE REVIEW

**Comment by vifactor** [comment]
@hannesa2 this MR on build jobs that I certainly did not touch. Is this a known issue?

**Comment by hannesa2** [comment]
Last `master` builds properly https://github.com/COVESA/dlt-viewer/actions  

But I see, when running from a fork the currently necessary variables for notarization are missing
@bunty95

**Comment by hannesa2** [comment]
After merge #539 it should work for you as well.
Please simply rebase

**Review by hannesa2 — APPROVED** [review]

**Comment by alexmucde** [comment]
@vifactor Is this ready for merge? Perhaps you can set the merge label, when the PR is ready for merge.

**Comment by vifactor** [comment]
@alexmucde yes, this is ready to merge. regarding labels, I do not think I have rights to add them

**Pull request merged**
