### PR TITLE
Include_fix: Corrected all qdlt includes

### PR DESCRIPTION
**Pull request by stephanvoigt**
* tested with Qt 5.15.2 and Qt 6.2.2
* tested on Windows (MSVC 2019) and Linux (gcc 11)

* QDltPlugin doesn't need forwarded classes anymore
* moved includes from qdlt.h into respective headers

* analysis with clang and clazy now possible

### CODE REVIEW

**Comment by alexmucde** [comment]
@stephanvoigt 
Thanks for the contribution. Several checks fails, please check.
Please allso add the signed off statement to the commit message.
The PR is very big. Perhaps you can also split the changes in smaller PRs, so that we can do a step by step integration.

**Comment by stephanvoigt** [comment]
Added signed-off statement.

In Visual Studio 2019 this PR builds without issues. The log states that '_timezone' is not known.
But '_timezone' is an builtin type and should be present in Visual Studio 2017 as well.
I will try to get my hands on Visual Studio 2017 and investigate further.

As for the size. Because I cleansed the usage of qdlt.h, I can't reduce the size of this PR.

**Comment by alexmucde** [comment]
@stephanvoigt Sorry for the delay, i had very busy weeks. We have now a lot of conflicts, because of some other pull reuests in between. Can you provide a new pull request with all your changes updated for the master and close the current pull request?

**Comment by alexmucde** [comment]
Replaced by QT 6 support code changes #324

**Pull request closed without merging**
